### 1. Load the dataset into python environment.

In [33]:
# include necessary libraries
import pandas as pd

In [2]:
data = pd.read_csv(r'/content/titanic_dataset .csv')

In [3]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### 2. Do all the necessary pre-processing steps.

In [6]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
# Dropping unrequired columns

data = data.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [8]:
data.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [9]:
# Handling missing values

data['Age'].fillna(data['Age'].median(), inplace=True)

In [10]:
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

In [11]:
data.dropna(subset=['Fare'], inplace=True)

In [12]:
# Converting categorical to numerical

data['Sex'] = data['Sex'].map({'male' : 0, 'female' : 1})

In [13]:
data = pd.get_dummies(data, columns=['Embarked'], drop_first=True)

In [14]:
# Separating feature and target variable

X = data.drop('Survived', axis=1) ### feature variable
y = data['Survived']              ### target variable

In [15]:
X

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         3    0  22.0      1      0   7.2500       False        True
1         1    1  38.0      1      0  71.2833       False       False
2         3    1  26.0      0      0   7.9250       False        True
3         1    1  35.0      1      0  53.1000       False        True
4         3    0  35.0      0      0   8.0500       False        True
..      ...  ...   ...    ...    ...      ...         ...         ...
886       2    0  27.0      0      0  13.0000       False        True
887       1    1  19.0      0      0  30.0000       False        True
888       3    1  28.0      1      2  23.4500       False        True
889       1    0  26.0      0      0  30.0000       False       False
890       3    0  32.0      0      0   7.7500        True       False

[891 rows x 8 columns]

In [16]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [17]:
# Scaling

from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
X = scaler.fit_transform(X)

In [20]:
X

array([[ 0.82737724, -0.73769513, -0.56573646, ..., -0.50244517,
        -0.30756234,  0.61583843],
       [-1.56610693,  1.35557354,  0.66386103, ...,  0.78684529,
        -0.30756234, -1.62380254],
       [ 0.82737724,  1.35557354, -0.25833709, ..., -0.48885426,
        -0.30756234,  0.61583843],
       ...,
       [ 0.82737724,  1.35557354, -0.1046374 , ..., -0.17626324,
        -0.30756234,  0.61583843],
       [-1.56610693, -0.73769513, -0.25833709, ..., -0.04438104,
        -0.30756234, -1.62380254],
       [ 0.82737724, -0.73769513,  0.20276197, ..., -0.49237783,
         3.25137334, -1.62380254]])

### 3. Create KNN and SVM models.

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [22]:
knn_model = KNeighborsClassifier()
svm_model = SVC()

In [23]:
knn_model

KNeighborsClassifier()

### 4. Do k-fold and stratified stratified k-fold cross validation techniques and find the average accuracy score of the models.

In [24]:
# K-fold cross-validation for KNN

from sklearn.model_selection import cross_val_score

In [25]:
knn_scores = cross_val_score(knn_model, X, y, cv = 5)

In [26]:
knn_accuracy_avg = knn_scores.mean()

In [27]:
knn_scores

array([0.79888268, 0.78089888, 0.83707865, 0.82022472, 0.82022472])

In [28]:
knn_accuracy_avg

0.811461929571276

In [29]:
# Stratified k-fold cross-validation for SVM

from sklearn.model_selection import StratifiedKFold

In [30]:
svm_scores = cross_val_score(svm_model, X, y, cv = 5)

In [31]:
svm_accuracy_avg = svm_scores.mean()

In [32]:
svm_accuracy_avg

0.827154604230745